site_name: Meditation Course on the Six Senses
site_url: https://bdhrs.github.io/meditation-course-on-the-six-senses/
use_directory_urls: true
site_dir: ../output/Meditation Course on the Six Senses

theme:
  
  name: material
  logo: assets/images/six-senses.svg
  
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  
  features:
    # Make sure navigation.tabs is NOT included here
    - navigation.sections
    - navigation.collapse
    # PWA features
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  
  navigation:
    prev: true
    next: true
  
  plugins:
    - navigation:
        instant: true

extra_javascript:
  - assets/js/custom.js
  - assets/js/rsw.js

extra_css:
  - assets/css/custom.css

# PWA Configuration
extra:
  manifest: manifest.webmanifest
  
plugins:
  - search

use_directory_urls: false

docs_dir: docs
