site_name: Meditation Course on the Six Senses
site_url: '' # Important for relative path resolution
use_directory_urls: true
site_dir: ../output/Meditation Course on the Six Senses

theme:
  
  name: material 
  
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  
  features:
    # Make sure navigation.tabs is NOT included here
    - navigation.sections
    - navigation.collapse  
  
  navigation:
    prev: true
    next: true
  
  plugins:
    - navigation:
        instant: true

extra_javascript:
  - assets/js/custom.js

extra_css:
  - assets/css/custom.css

use_directory_urls: false
