name: Deploy Custom Website to GitHub Pages
on:
  push:
    paths:
      - 'website_project/**'
      - 'source/**'
      - '.github/workflows/Deploy to GitHub Pages.yaml'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        
      - name: Install dependencies
        run: uv sync
      
      - name: Build custom website
        run: uv run website_project/build.py --mode online
      
      - name: Create .nojekyll file
        run: touch "output/Meditation Course on the Six Senses/.nojekyll"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'output/Meditation Course on the Six Senses'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4