name: Deploy to GitHub Pages
on:
  push:
    paths:
      - 'mkdocs_project/docs/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./mkdocs_project/docs
          github_token: ${{ secrets.GITHUB_TOKEN }}