name: Deploy to GitHub Pages
on:
  push:
    paths:
      - 'mkdocs_project/docs/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy files
        run: |
          mkdir -p public
          cp -r mkdocs_project/docs/* public/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'